export enum ServiceStatuses {
  SCHEDULED = 'SCHEDULED',
  APPROVED = 'APPROVED',
  WAITING_FOR_APPROVAL = 'WAITING FOR APPROVAL',
  WAITING_FOR_REVIEW = 'WAITING FOR REVIEW',
  COMPLETED = 'COMPLETED',
}
