export enum NotificationTypes {
  PM_INTERNAL = 'PM_INTERNAL',
  PM_EXTERNAL = 'PM_EXTERNAL',
  TASK = 'TASK',
  SPARE_PART = 'SPARE_PART',
  ASSET = 'ASSET',
  ASSET_PACKAGE = 'ASSET_PACKAGE',
  PROJECT = 'PROJECT',
  SUB_PROJECT = 'SUB_PROJECT',
}
